# Imports the shared Azure CI tools
resources:
  repositories:
    - repository: templates
      type: github
      name: shotgunsoftware/tk-ci-tools
      ref: refs/heads/add_black
      endpoint: shotgunsoftware

# Configures CI to be triggered by changes to any branches and on tag creation.
trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - v*

# This pulls in a variable group from Azure. Variables can be encrypted or not.
variables:
- group: deploy-secrets

jobs:
- template: build-pipeline.yml@templates
